local HttpRbxApiService = game:GetService("HttpRbxApiService")
local HttpService = game:GetService("HttpService")
local Selection = game:GetService("Selection")

local ApplyColorCopy = require(script.Parent.ApplyColorCopy)
local ApplyConfigurationValues = require(script.Parent.ApplyConfigurationValues)
local Branding = require(script.Parent.Branding)
local Logger = require(script.Parent.Logger)
local ExtractedUtil = require(script.Parent.ExtractedUtil)
local ClassicStableDecompiler = require(script.Parent.Parent.OldCompilers["Stable JSON v2.1.0"])
local LuaEncode = require(script.Parent.Parent.MBEPackages.LuaEncode)
local Compilers = require(script.Parent.Compilers)
local CreateOutputScript = require(script.Parent.CreateOutputScript)

local compilerSettings = {
	Offset = Vector3.zero,
	ShowTODO = false,
}

function ModernDecompile(content): (Model?, string?)
	local model
	local success, err = ExtractedUtil.HistoricEvent("Decompile", "Decompile Model", function()
		if content:sub(1, 4) == "http" then
			content = HttpRbxApiService:GetAsync(content)
		end

		local instances, saveData = Compilers:GetSelectedCompiler():Decompile(content, compilerSettings)

		model = Instance.new("Model")
		model.Name = "Decompilation"

		for _, instance in instances do
			instance.Parent = model
		end

		local _, bounds = model:GetBoundingBox()

		model.Parent = workspace

		model:MoveTo(ExtractedUtil.GetInsertPoint(bounds.Magnitude * 2, bounds.Y / 2))

		-- Create a script to put the details in
		local source = `-- The following is a summary of the data contained in the model's save format generated by LuaEncode.\n-- Your model has been selected in the explorer. \nreturn {LuaEncode(saveData, {
			Prettify = true
		})}`
		local details_script = CreateOutputScript(source, Branding.NAME_ABBREVIATION .. "Details", true)
		if details_script then
			details_script.Parent = model
		end

		-- Select model
		Selection:Set({model})

		Logger.print("SUCCESSFULLY DECOMPILED DATA")
	end)
	Logger.print(`Modern decompile returned {success}, {err}`)
	if success then
		return model, nil
	end
	return nil, err
end

function ClassicDecompile(content)
	if content:sub(1, 4) == "http" then
		content = HttpService:GetAsync(content)
	end

    local decompile_position = CFrame.new(ExtractedUtil.GetInsertPoint(32))
	local decompiled_parts = ClassicStableDecompiler.Decompile(decompile_position, content)

	local container_model = Instance.new("Model")

	for _, part in decompiled_parts do
		part.Parent = container_model
		ApplyColorCopy(part)

		for _, config in part:GetDescendants() do
			if not config:IsA("ValueBase") then continue end
			ApplyConfigurationValues(nil, part, config, config.Value)
		end
	end

	container_model.Name = `{Branding.NAME_ABBREVIATION}_Decompile`
	container_model.Parent = workspace

	Selection:Set({container_model})
end

return function(save_string: string)
	Logger.print("DECOMPILE STARTED")

	local model = ModernDecompile(save_string)

	if model then
		Logger.print("DECOMPILE SUCCESS")
	else
		Logger.print("MODERN DECOMPILE FAILED, TRYING CLASSIC DECOMPILER")

		local ok, _ = xpcall(ClassicDecompile :: any, function(err)
			Logger.warn("CLASSIC DECOMPILE FAILED WITH ERROR", err, debug.traceback())
		end, save_string)

		if ok then
			Logger.print("CLASSIC DECOMPILE SUCCEEDED")
		end
	end
end
